### ISSUE TITLE
Issue with SystemJS ^0.20.0

### ISSUE THREAD

**Issue by ArmorDarks** [yoavniran/jest-jspm#2]
Hi

We recently updated to JSPM 0.17.0-beta.41, which updated SystemJS to version above 0.20.0.

SystemJS 0.20.0 introduced some breaking changes ([SystemJS 0.20.0 release notes](https://github.com/systemjs/systemjs/releases/tag/0.20.0), and do not forget to check newer released, there were some after 0.20.0).

It also, probably, changed format of `system.js` file.

Now, when we try to use `jest-jspm`, we're getting following error:

```
> node tests/utils/jest.js --watch                                                                 
                                                                                                   
J:\Work\Kotsu\github\jspm.config.js:1                                                              
(function (exports, require, module, __filename, __dirname) { SystemJS.config({                    
                                                              ^                                    
                                                                                                   
ReferenceError: SystemJS is not defined                                                            
    at Object.<anonymous> (J:\Work\Kotsu\github\jspm.config.js:1:63)                               
    at Module._compile (module.js:571:32)                                                          
    at Object.Module._extensions..js (module.js:580:10)                                            
    at Module.load (module.js:488:32)                                                              
    at tryModuleLoad (module.js:447:12)                                                            
    at Function.Module._load (module.js:439:3)                                                     
    at Module.require (module.js:498:17)                                                           
    at require (internal/module.js:20:19)                                                          
    at getModuleFromAbsBasePath (J:\Work\Kotsu\github\node_modules\jest-jspm\lib\utils.js:23:56)   
    at exports.default (J:\Work\Kotsu\github\node_modules\jest-jspm\lib\jspmConfigLoader.js:14:39) 
```

I guess due to SystemJS changes, it no longer properly loaded?

**Comment by ArmorDarks** [comment]
Ok, it seems that there is an issue with require. I do not like that solution, but so far don't see any other alternatives.

Here https://github.com/yoavniran/jest-jspm/blob/master/src/jspmConfigLoader.js#L7

1. `systemJS` should be renamed to `SystemJS`
2. It have to be explicitly set to global variable before require config itself with

   ```js
   global.SystemJS = SystemJS
   ````

This fixes described issue. However, for some reason with this version of SystemJS mappings does not work for Jest, I have after generating Jest config following:

```js
{ moduleFileExtensions: [ 'coffee', 'js' ],
  transform:
   { '^.+\.js?$': 'babel-jest',
     '^.+\.coffee$': '<rootDir>/tests/utils/jest-preprocessor.js' },
  testPathIgnorePatterns: [ '/node_modules/', '/jspm_packages/' ],
  testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.(coffee|js)?$',
  moduleNameMapper:
   { '^plugin-babel$': '///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/systemjs-plugin-babel@0.0.21',
     '^plugin-babel/(.*)': '///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/systemjs-plugin-babel@0.0.21/$1',
     '^jquery$': '///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/jquery@3.2.0',
     '^jquery/(.*)': '///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/jquery@3.2.0/$1',
     '^npm:(.*)': '<rootDir>/jspm_packages/npm/$1',
     '^github:(.*)': '<rootDir>/jspm_packages/github/$1' },
  moduleDirectories: [ 'node_modules', 'jspm_packages/npm', 'jspm_packages/github' ],
  rootDir: 'J:\\Work\\Kotsu\\github' }
```

But Jest can't import `jquery`, despite with older SystemJS it was possible:

```
 FAIL  tests\modules\crumble.test.js
  ● Test suite failed to run

    Cannot find module 'jquery' from 'crumble.test.js'

      at Resolver.resolveModule (node_modules\jest-resolve\build\index.js:169:17)
      at Object.<anonymous> (tests\modules\crumble.test.js:4:15)
```

**Comment by ArmorDarks** [comment]
@yoavniran 

And here is config from JSPM 0.17.0-beta.21 with SystemJS v0.19.31 which works even without fixing issue above:

```js
{ moduleFileExtensions: [ 'coffee', 'js' ],
  transform:
   { '^.+\.js?$': 'babel-jest',
     '^.+\.coffee$': '<rootDir>/tests/utils/jest-preprocessor.js' },
  testPathIgnorePatterns: [ '/node_modules/', '/jspm_packages/' ],
  testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.(coffee|js)?$',
  moduleNameMapper:
   { '^plugin-babel$': 'systemjs-plugin-babel@0.0.21',
     '^plugin-babel/(.*)': 'systemjs-plugin-babel@0.0.21/$1',
     '^jquery$': 'jquery@3.2.0',
     '^jquery/(.*)': 'jquery@3.2.0/$1',
     '^npm:(.*)': '<rootDir>/jspm_packages/npm/$1',
     '^github:(.*)': '<rootDir>/jspm_packages/github/$1' },
  moduleDirectories: [ 'node_modules', 'jspm_packages/npm', 'jspm_packages/github' ],
  rootDir: 'J:\\Work\\Kotsu\\github' }
```

Jest able to load JSPM modules.

Here is the difference (left — on SystemJS 0.19.31, right — SystemJS ^0.20.0)

![merge_2017-03-17_17-31-09](https://cloud.githubusercontent.com/assets/4460311/24050488/a13dcab2-0b37-11e7-860a-7ebebcb0e6d3.png)

**Comment by ArmorDarks** [comment]
@yoavniran any ETA on this? We really would like to make next release of Kotsu, but this thing is blocking right now :(

**Comment by yoavniran** [comment]
hi @ArmorDarks unfortunately i havent had time to dig into this.
i hope i can find time this week but cant promise im afraid.

one question does come to mind from all the info you posted here (thanks for that!) - it looks like your jspm_packages isnt in the root folder of your project, yet it doesnt look like you configured jest-jspm accordingly. 
you say it works with sysjs 0.19 so i guess its not an issue although it does surprise me

**Comment by ArmorDarks** [comment]
@yoavniran I understand, it isn't mandatory work after all. Just wanted to know status :)

> one question does come to mind from all the info you posted here (thanks for that!) - it looks like your jspm_packages isnt in the root folder of your project, yet it doesnt look like you configured jest-jspm accordingly.

It is in root. You can see full structure [here](https://github.com/LotusTM/Kotsu).

When you will do `npm install` (which will invoke `jspm install`), you will get following structure:

![explorer_2017-03-27_20-21-31](https://cloud.githubusercontent.com/assets/4460311/24368919/02b2b118-132b-11e7-8298-8a9fbb65bcda.png)

And here you see how exactly `jest-jspm` configurated: https://github.com/LotusTM/Kotsu/blob/master/tests/utils/jest.js

> you say it works with sysjs 0.19 so i guess its not an issue although it does surprise me

Yeap, it worked. There were quite a lot of breaking changes in SystemJS 0.20.0, so maybe it somehow related.

**Comment by ArmorDarks** [comment]
Ah, the issue turned out to be trivial. SystemJS 0.20.0 and above changed output of `SystemJS.getConfig()`.

I've just logged out output of this [line](https://github.com/yoavniran/jest-jspm/blob/master/src/jspmConfigLoader.js#L13)

Here is SystemJS v0.19.47 output:

```js
{ paths:
   { 'npm:': 'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/',
     'kotsu/': 'file:///J:/Work/Kotsu/github/assets/scripts/source/scripts/' },
  meta: { '*.json': { loader: 'systemjs-plugin-json' } },
  baseURL: 'file:///J:/Work/Kotsu/github/assets/scripts/',
  map:
   { 'plugin-babel': 'npm:systemjs-plugin-babel@0.0.21',
     'systemjs-plugin-json': 'npm:systemjs-plugin-json@0.3.0',
     jquery: 'npm:jquery@3.2.0' },
  scriptSrc: 'J:\\Work\\Kotsu\\github\\jspm_packages\\system.js',
  warnings: false,
  defaultJSExtensions: false,
  pluginFirst: false,
  loaderErrorStack: false,
  packages: { 'file:///J:/Work/Kotsu/github/assets/scripts/source/scripts': { main: 'main.js', format: 'esm', meta: [Object] } },
  packageConfigPaths:
   [ 'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/@*/*.json',
     'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/*.json' ],
  bundles: {},
  depCache: {},
  transpiler: 'plugin-babel',
  production: false }
```

Here is SystemJS v0.20.11 Dev (latest release) output:

```js
{ baseURL: 'file:///J:/Work/Kotsu/github/assets/scripts/',
  map:
   { 'plugin-babel': 'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/systemjs-plugin-babel@0.0.21',
     'systemjs-plugin-json': 'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/systemjs-plugin-json@0.3.0',
     jquery: 'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/jquery@3.2.0' },
  paths: { 'npm:': 'jspm_packages/npm/', 'kotsu/': 'source/scripts/' },
  packages:
   { 'file:///J:/Work/Kotsu/github/assets/scripts/source/scripts':
      { defaultExtension: 'js',
        main: 'main.js',
        format: 'esm',
        meta: [Object],
        map: undefined,
        configured: false } },
  packageConfigPaths:
   [ 'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/@*/*.json',
     'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/*.json' ],
  depCache: {},
  meta: { '*.json': { loader: 'systemjs-plugin-json' } },
  bundles: {},
  transpiler: 'plugin-babel',
  warnings: false,
  pluginFirst: false,
  production: false,
  wasm: false }
```

And here is the diff

![merge_2017-04-01_20-15-54](https://cloud.githubusercontent.com/assets/4460311/24580823/09ab8be8-1718-11e7-8fa4-5197757813cb.png)

As you can see, changes are massive and obviously all paths substitution magick in `jest-jspm` simply doesn't work anymore, it should be updated to support new SystemJS structure.

**Comment by ArmorDarks** [comment]
Ok, to make changes a bit clearer, I've normilized both configs, so that they have similar property order.

SystemJS 0.19+:

```js
{
  baseURL: 'file:///J:/Work/Kotsu/github/assets/scripts/',
  map: {
    'plugin-babel': 'npm:systemjs-plugin-babel@0.0.21',
    'systemjs-plugin-json': 'npm:systemjs-plugin-json@0.3.0',
    jquery: 'npm:jquery@3.2.0'
  },
  paths: {
    'npm:': 'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/',
    'kotsu/': 'file:///J:/Work/Kotsu/github/assets/scripts/source/scripts/'
  },
  scriptSrc: 'J:\\Work\\Kotsu\\github\\jspm_packages\\system.js',
  defaultJSExtensions: false,
  loaderErrorStack: false,
  packages: {
    'file:///J:/Work/Kotsu/github/assets/scripts/source/scripts': {
      main: 'main.js',
      format: 'esm',
      meta: [Object]
    }
  },
  packageConfigPaths: [
    'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/@*/*.json',
    'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/*.json'
  ],
  meta: {
    '*.json': {
      loader: 'systemjs-plugin-json'
    }
  },
  bundles: {},
  depCache: {},
  transpiler: 'plugin-babel',
  warnings: false,
  pluginFirst: false,
  production: false
}
```

SystemJS 0.20+

```js
{
  baseURL: 'file:///J:/Work/Kotsu/github/assets/scripts/',
  map: {
    'plugin-babel': 'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/systemjs-plugin-babel@0.0.21',
    'systemjs-plugin-json': 'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/systemjs-plugin-json@0.3.0',
    jquery: 'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/jquery@3.2.0'
  },
  paths: {
    'npm:': 'jspm_packages/npm/',
    'kotsu/': 'source/scripts/'
  },
  packages: {
    'file:///J:/Work/Kotsu/github/assets/scripts/source/scripts': {
        defaultExtension: 'js',
        main: 'main.js',
        format: 'esm',
        meta: [Object],
        map: undefined,
        configured: false
      }
    },
  packageConfigPaths: [
    'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/@*/*.json',
    'file:///J:/Work/Kotsu/github/assets/scripts/jspm_packages/npm/*.json'
  ],
  meta: {
    '*.json': {
      loader: 'systemjs-plugin-json'
    }
  },
  bundles: {},
  depCache: {},
  transpiler: 'plugin-babel',
  warnings: false,
  pluginFirst: false,
  production: false,
  wasm: false
}
```

And here is the diff:

![merge_2017-04-01_20-35-27](https://cloud.githubusercontent.com/assets/4460311/24580956/c44f16a2-171a-11e7-9a71-59e80a00f9c5.png)

It is now much clearer what exactly changed.

Most important changes happened here. Seems like map now contains full paths:

![merge_2017-04-01_20-36-10](https://cloud.githubusercontent.com/assets/4460311/24580972/14ac5a24-171b-11e7-962a-f9d7fb0ee8f3.png)

**Comment by ArmorDarks** [comment]
Hi!

Any chances to finally fix this? :)

**Comment by jcrjaci** [comment]
Hi,

any updates?
